In [410]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
#The prediction of crop yield is based on soil, meteorological, environmental, and crop parameters,
#temperature, rainfall, and soil type

In [411]:
Yield = pd.read_csv('yield_df.csv')
Yield[Yield['Year']>=2008]

,Unnamed: 0,Area,Item,Year,hg/ha_yield,average_rain_fall_mm_per_year,pesticides_tonnes,avg_temp
75,75,Albania,Maize,2008,50000,1485.0,1069.54,16.71
76,76,Albania,Potatoes,2008,193878,1485.0,1069.54,16.71
77,77,Albania,Soybeans,2008,20000,1485.0,1069.54,16.71
78,78,Albania,Wheat,2008,40168,1485.0,1069.54,16.71
79,79,Albania,Maize,2009,55693,1485.0,1132.50,16.73
...,...,...,...,...,...,...,...,...
28237,28237,Zimbabwe,"Rice, paddy",2013,22581,657.0,2550.07,19.76
28238,28238,Zimbabwe,Sorghum,2013,3066,657.0,2550.07,19.76
28239,28239,Zimbabwe,Soybeans,2013,13142,657.0,2550.07,19.76
28240,28240,Zimbabwe,Sweet potatoes,2013,22222,657.0,2550.07,19.76
28241,28241,Zimbabwe,Wheat,2013,22888,657.0,2550.07,19.76

In [412]:
newYield = Yield[Yield['Year']>=2004]
# newYield = newYield.join(pd.get_dummies(newYield['Item']))
newYield = newYield.join(pd.get_dummies(newYield['Area']))
areaItem = pd.DataFrame(newYield,columns=['Area','Item'])

yieldItem = areaItem['Item'].unique()
yielArea =  areaItem['Area'].unique()
X = pd.DataFrame(newYield,columns=['Year','hg/ha_yield','average_rain_fall_mm_per_year','pesticides_tonnes','avg_temp'])
Y = newYield['Item']
Z = newYield['Area']
newYield = newYield.drop('Item',axis=1)
newYield = newYield.drop('Area',axis=1)
newYield = newYield.drop('Unnamed: 0',axis=1)
print(X.shape)
print(Y.shape)
# Year	hg/ha_yield	average_rain_fall_mm_per_year	pesticides_tonnes	avg_temp

(12449, 5)
(12449,)

In [413]:
from sklearn import preprocessing
x = newYield[['hg/ha_yield']].values.astype(float)
y = newYield[['average_rain_fall_mm_per_year']].values.astype(float)
z = newYield[['pesticides_tonnes']].values.astype(float)

min_max_scaler = preprocessing.MinMaxScaler()

x_scaled = min_max_scaler.fit_transform(x)
y_scaled = min_max_scaler.fit_transform(y)
z_scaled = min_max_scaler.fit_transform(z)
newYield['hg/ha_yield']=x_scaled
newYield['average_rain_fall_mm_per_year'] = y_scaled
newYield['pesticides_tonnes'] = z_scaled

In [414]:
# mat = newYield.corr()
# fig = plt.figure(figsize=(8,8))
# sb.heatmap(mat,vmax=.8,square = True)
# plt.show()

In [415]:
# for selected item 'crop' put all other item to '0' same goes for Area....
# def prediction(area,item):
# splitting data into training and test data
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size =0.18, random_state=100)

In [416]:
clf_entropy = DecisionTreeClassifier(criterion="entropy",random_state=100,max_depth=18,min_samples_leaf=8)
clf_entropy.fit(X_train,Y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=18, min_samples_leaf=8,
                       random_state=100)

In [417]:
Y_pred = clf_entropy.predict(X_test)

In [418]:
from sklearn.metrics import r2_score
# r2_score(Y_test,Y_pred)
print(classification_report(Y_test,Y_pred))
print('Accuracy :', accuracy_score(Y_test,Y_pred)*100 )

                      precision    recall  f1-score   support

             Cassava       0.74      0.80      0.77       168
               Maize       0.76      0.77      0.76       313
Plantains and others       0.74      0.70      0.72        50
            Potatoes       0.89      0.86      0.88       339
         Rice, paddy       0.76      0.76      0.76       254
             Sorghum       0.73      0.73      0.73       234
            Soybeans       0.77      0.78      0.78       251
      Sweet potatoes       0.79      0.80      0.80       257
               Wheat       0.74      0.73      0.73       300
                Yams       0.76      0.71      0.73        75

            accuracy                           0.78      2241
           macro avg       0.77      0.76      0.77      2241
        weighted avg       0.78      0.78      0.78      2241

Accuracy : 77.59928603302097